In [1]:
import numpy as np

#here I am defining an Rank-1 array so we cannot decide its column or row
a = np.random.randn(5)

In [2]:
print(a)

[ 1.72354943  0.24407895  0.87138067  0.35850736 -1.88946408]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T) #used for Transpose matrix

[ 1.72354943  0.24407895  0.87138067  0.35850736 -1.88946408]


In [5]:
print((a.T).shape)

(5,)


In [6]:
print(np.dot(a, a.T))

7.488103454354027


Use These Vectors where you need to predict the behaviour of matrix, it can be a row or column

In [7]:
b = np.random.randn(5, 1)

In [8]:
print(b)

[[ 1.25524843]
 [ 0.08114891]
 [-0.48703409]
 [ 0.55678474]
 [-0.069693  ]]


In [9]:
print(b.shape)

(5, 1)


In [10]:
print(b.T)

[[ 1.25524843  0.08114891 -0.48703409  0.55678474 -0.069693  ]]


In [11]:
print(np.dot(b, b.T))

[[ 1.57564862  0.10186204 -0.61134878  0.69890317 -0.08748203]
 [ 0.10186204  0.00658515 -0.03952228  0.04518247 -0.00565551]
 [-0.61134878 -0.03952228  0.23720221 -0.27117315  0.03394287]
 [ 0.69890317  0.04518247 -0.27117315  0.31000925 -0.038804  ]
 [-0.08748203 -0.00565551  0.03394287 -0.038804    0.00485711]]
