In [1]:
print('Hello from Pytorch/tensors.py')

Hello from Pytorch/tensors.py


Tensor is a number, vector, matrix, or any multi-dimensional array.

In [2]:
import torch

#number
t1 = torch.tensor(4.)
print(t1)

tensor(4.)


In [8]:
t1.dtype

torch.float32

In [3]:
#vector
t2 = torch.tensor([1., 2, 3, 4])
print(t2)

tensor([1., 2., 3., 4.])


In [4]:
#matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [5]:
#3d array
t4 = torch.tensor([
        [[11, 12, 13],
        [13, 14, 15]],
        [[15, 16, 17],
        [17, 18, 19.]]
    ])
print(t4)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


In [6]:
#tensor attributes
print(t1.shape)

torch.Size([])


In [9]:
print(t2.shape)

torch.Size([4])


In [10]:
print(t3.shape)

torch.Size([3, 2])


In [11]:
print(t4.shape)

torch.Size([2, 2, 3])


Tensor operations and gradients

In [7]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


This method will compute derivatives

In [12]:
y.backward()

Display derivatives and .grad method of tensor w and b will return the derivative of y with respect to w and b

In [13]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Note: dy/dx: None because requires_grad=False